config/routes.rb
Rails.application.routes.draw do

  get 'services', to: 'services#index'
  get 'serviceTypes', to: 'service_types#index'
  get 'brands', to: 'brands#index'
  get 'clients', to: 'clients#index'
  get 'colors', to: 'colors#index'
  get 'officials', to: 'officials#index'
  get 'positions', to: 'positions#index'
  get 'vehicleModels', to: 'vehicle_models#index'
  get 'vehicles', to: 'vehicles#index'

  get 'services/new', to: 'services#new', as: 'service_new'
  post 'services', to: 'services#create'

  get 'service/type/new', to: 'service_types#new', as: 'service_types_new'
  post 'service_types', to: 'service_types#create'

  get 'brand/new', to: 'brands#new', as: 'brands_new'
  post 'brands',to: 'brands#create'

  get 'client/new', to: 'clients#new', as: 'clients_new'
  post 'clients', to: 'clients#create'

  get 'color/new', to: 'colors#new', as: 'color_new'
  post 'colors', to: 'colors#create'

  get 'officials/new', to: 'officials#new', as: 'officials_new'
  post 'officials', to: 'officials#create'

  get 'position/new', to: 'positions#new',  as: 'position_new'
  post 'positions', to: 'positions#create'

  get 'vehicleModels/new', to: 'vehicle_models#new', as: 'models_new'
  post 'vehicle_models', to: 'vehicle_models#create'

  get 'vehicle/new', to: 'vehicles#new', as: 'vehicle_new'
  post 'vehicles', to: 'vehicles#create'

  get 'brand/:id', to: 'brands#show', as: 'brand'
  get 'brand/:id/edit', to: 'brands#edit', as: 'brand_edit'
  patch 'brand/:id', to: 'brands#update'

  get 'client/:id', to: 'clients#show', as: 'client'
  get 'client/:id/edit', to: 'clients#edit', as: 'client_edit'
  patch 'client/:id', to: 'clients#update'

  get 'color/:id', to: 'colors#show', as: 'color'
  get 'color/:id/edit', to: 'colors#edit', as: 'color_edit'
  patch 'color/:id', to: 'colors#update'

  get 'official/:id', to: 'officials#show', as: 'official'
  get 'official/:id/edit', to: 'officials#edit', as: 'official_edit'
  patch 'official/:id', to: 'officials#update'

  get 'position/:id', to: 'positions#show', as: 'position'
  get 'position/:id/edit', to: 'positions#edit', as: 'position_edit'
  patch 'position/:id', to: 'positions#update'

  get 'vehicle/model/:id', to: 'vehicle_models#show', as: 'vehicle_model'
  get 'vehicle/model/:id/edit', to: 'vehicle_models#edit', as: 'vehicle_model_edit'
  patch 'vehicle/model/:id', to: 'vehicle_models#update'

  get 'service/type/:id', to: 'service_types#show', as: 'service_type'
  get 'service/type/:id/edit', to: 'service_types#edit', as: 'service_type_edit'
  patch 'service/type/:id', to: 'service_types#update'

  get 'service/:id', to: 'services#show', as: 'service'
  get 'service/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'service/:id', to: 'services#update'

  get 'vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get 'vehicle/:id/edit', to: 'vehicles#edit', as: 'vehicle_edit'
  patch 'vehicle/:id', to: 'vehicles#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
 has_many :vehicle_models
 validates :brand_name, presence: true

 def self.search(term, page)
  if term
   where('brand_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('brand_name ASC')
  else
   paginate(page: page, per_page: 4).order('brand_name ASC')
  end
 end

end

app/models/client.rb
class Client < ApplicationRecord
  validates :address, presence: true
  validates :birth_date, presence: true
  validates :customer_type, presence: true
  validates :document_number, presence: true, uniqueness: true
  validates :limite_credito, presence: true
  validates :first_name, presence: true
  validates :gender, presence: true
  validates :last_name, presence: true
  validates :telephone, presence: true, numericality: true

  def self.search(term, page)
    if term
      where('document_number LIKE ? or first_name LIKE ? or last_name LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('document_number ASC')
    else
      paginate(page: page, per_page: 4).order('document_number ASC')
    end
  end

  def client_for_select
    "#{last_name}"
  end
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :vehicles
  validates :color_name, allow_blank:false, presence: true

  def self.search(term, page)
    if term
      where('color_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('color_name ASC')
    else
      paginate(page: page, per_page: 4).order('color_name ASC')
    end
  end

  def color_for_select
    "#{color_name}"
  end

end

app/models/official.rb
class Official < ApplicationRecord
    belongs_to :position, optional: true
    validates :document_number, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :address, presence: true

    def self.search(term, page)
        if term
            where('address LIKE ? or first_name LIKE ? or last_name LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('last_name ASC')
        else
            paginate(page: page, per_page: 4).order('last_name ASC, "%#{term}%"')
        end
    end

end

app/models/position.rb
class Position < ApplicationRecord
  has_many :officials
  validates :position_name, presence: true

  def self.search(term, page)
    if term
      where('position_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('position_name ASC')
    else
      paginate(page: page, per_page: 4).order('position_name ASC')
    end
  end

  def position_for_select
    "#{position_name}"
  end

end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :service_type, optional: true
  validates :price, presence: true, numericality: true
  validates :service_name, presence: true

  def self.search(term, page)
    if term
      where('service_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('service_name ASC')
    else
      paginate(page: page, per_page: 4).order('service_name ASC')
    end
  end

end

app/models/service_type.rb
class ServiceType < ApplicationRecord
  has_many :services
  validates :service_type_name, presence: true

  def self.search(term, page)
    if term
      where('service_type_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('service_type_name ASC')
    else
      paginate(page: page, per_page: 4).order('service_type_name ASC')
    end
  end

  def service_type_for_select
      "#{service_type_name}"
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :color, optional: true
  belongs_to :vehicle_model, optional: true


  def self.search(term, page)
  if term
     where('patent_number LIKE ? or chassis_number LIKE ?', "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('patent_number ASC')
    else
      paginate(page: page, per_page: 4).order('patent_number ASC')
    end
  end

end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
    belongs_to :brand
    has_many :vehicles
    validates :brand_id, presence: true
    validates :year_of_production, presence: true
    validates :vehicle_model_name, presence: true

    def self.search(term, page)
        if term
            where('vehicle_model_name LIKE ? or year_of_production LIKE ?', "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('vehicle_model_name ASC')
        else
            paginate(page: page, per_page: 4).order('vehicle_model_name ASC')
        end
    end

    def model_for_select
        "#{vehicle_model_name}"
    end

end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/officials_helper.rb
module OfficialsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/positions/_form_position.html.erb
<h2>
  <%= title %>
  <%= link_to "", positions_path, class: 'btn btn-secondary fas fa-undo-alt rounded-1 float-right form-inline' %>
</h2>

<%= form_for @position do |f| %>

  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12 text-center">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <br>
                  <br>
                  <br>
                  <label><b>Position</b></label>
                  <br>
                  <%= f.text_field :position_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here position name', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <%= f.submit :Create, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/positions/edit.html.erb
<h2>
  Edit Position
  <%= link_to "Return", positions_path, class: 'btn btn-secondary rounded-1 float-right form-inline' %>
</h2>

<%= form_for @edit_position do |f| %>

  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12 text-center">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <br>
                  <br>
                  <br>
                  <label><b>Position</b></label>
                  <br>
                  <%= f.text_field :position_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here position name', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <%= f.submit :Update, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/positions/index.html.erb
 <h1>
   Listing positions

   <%= form_tag positions_path, method: :get, :class => 'float-right form-inline' do %>
     <%= text_field_tag :term, params[:term], autofocus: true, :class => 'form-control mr-sm-2', :type => 'search', :placeholder => 'Search', autocomplete: 'off' %>
     <%= submit_tag 'Search', nombre: nil, :class => 'btn btn-outline-success my-2 my-sm-0' %>&nbsp&nbsp&nbsp&nbsp
     <%= link_to "", position_new_path, class: 'btn btn-primary fas fa-plus rounded-1 float-right form-inline' %>
   <% end %>

 </h1>
<br>
<br>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Position</th>
    <th>Options</th>
  </tr>
  </tr>
  </thead>

  <% @get_position_list.each do |position| %>
    <tbody>
    <tr>
      <th><%= position.position_name %></th>
      <td>
        &nbsp&nbsp<%= link_to "", position_edit_path(position),  class:'btn btn-outline rounded-0 fas fa-pencil-alt fa-2x' %>&nbsp&nbsp
      </td>
    </tr>
    </tbody>
  <% end %>
</table>

 <div class="apple_pagination">
   <div class="page_info">
     <%= page_entries_info @get_position_list %>
   </div>
   <%= will_paginate @get_position_list, :container => false %>
 </div>

app/views/positions/new.html.erb
<%= render "positions/form_position", title: "New Position" %>