config/routes.rb
Rails.application.routes.draw do

  get 'services', to: 'services#index'
  get 'serviceTypes', to: 'service_types#index'
  get 'brands', to: 'brands#index'
  get 'clients', to: 'clients#index'
  get 'colors', to: 'colors#index'
  get 'officials', to: 'officials#index'
  get 'positions', to: 'positions#index'
  get 'vehicleModels', to: 'vehicle_models#index'
  get 'vehicles', to: 'vehicles#index'

  get 'services/new', to: 'services#new', as: 'service_new'
  post 'services', to: 'services#create'

  get 'service/type/new', to: 'service_types#new', as: 'service_types_new'
  post 'service_types', to: 'service_types#create'

  get 'brand/new', to: 'brands#new', as: 'brands_new'
  post 'brands',to: 'brands#create'

  get 'client/new', to: 'clients#new', as: 'clients_new'
  post 'clients', to: 'clients#create'

  get 'color/new', to: 'colors#new', as: 'color_new'
  post 'colors', to: 'colors#create'

  get 'officials/new', to: 'officials#new', as: 'officials_new'
  post 'officials', to: 'officials#create'

  get 'position/new', to: 'positions#new',  as: 'position_new'
  post 'positions', to: 'positions#create'

  get 'vehicleModels/new', to: 'vehicle_models#new', as: 'models_new'
  post 'vehicle_models', to: 'vehicle_models#create'

  get 'vehicle/new', to: 'vehicles#new', as: 'vehicle_new'
  post 'vehicles', to: 'vehicles#create'

  get 'brand/:id', to: 'brands#show', as: 'brand'
  get 'brand/:id/edit', to: 'brands#edit', as: 'brand_edit'
  patch 'brand/:id', to: 'brands#update'

  get 'client/:id', to: 'clients#show', as: 'client'
  get 'client/:id/edit', to: 'clients#edit', as: 'client_edit'
  patch 'client/:id', to: 'clients#update'

  get 'color/:id', to: 'colors#show', as: 'color'
  get 'color/:id/edit', to: 'colors#edit', as: 'color_edit'
  patch 'color/:id', to: 'colors#update'

  get 'official/:id', to: 'officials#show', as: 'official'
  get 'official/:id/edit', to: 'officials#edit', as: 'official_edit'
  patch 'official/:id', to: 'officials#update'

  get 'position/:id', to: 'positions#show', as: 'position'
  get 'position/:id/edit', to: 'positions#edit', as: 'position_edit'
  patch 'position/:id', to: 'positions#update'

  get 'vehicle/model/:id', to: 'vehicle_models#show', as: 'vehicle_model'
  get 'vehicle/model/:id/edit', to: 'vehicle_models#edit', as: 'vehicle_model_edit'
  patch 'vehicle/model/:id', to: 'vehicle_models#update'

  get 'service/type/:id', to: 'service_types#show', as: 'service_type'
  get 'service/type/:id/edit', to: 'service_types#edit', as: 'service_type_edit'
  patch 'service/type/:id', to: 'service_types#update'

  get 'service/:id', to: 'services#show', as: 'service'
  get 'service/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'service/:id', to: 'services#update'

  get 'vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get 'vehicle/:id/edit', to: 'vehicles#edit', as: 'vehicle_edit'
  patch 'vehicle/:id', to: 'vehicles#update'

end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
    belongs_to :brand
    has_many :vehicles
    validates :brand_id, presence: true
    validates :year_of_production, presence: true
    validates :vehicle_model_name, presence: true

    def self.search(term, page)
        if term
            where('vehicle_model_name LIKE ? or year_of_production LIKE ?', "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('vehicle_model_name ASC')
        else
            paginate(page: page, per_page: 4).order('vehicle_model_name ASC')
        end
    end

    def model_for_select
        "#{vehicle_model_name}"
    end

end

app/controllers/vehicle_models_controller.rb
class VehicleModelsController < ApplicationController
  def index
    @get_vehicle_models = VehicleModel.search(params[:term],params[:page])
  end
  def new
    @vehicle_model = VehicleModel.new
  end

  def edit
    @edit_vehicle_model = VehicleModel.find(params[:id])
  end

  def update
    @update_position = VehicleModel.find(params[:id])
    if @update_position.update(vehicle_model_params)
      redirect_to vehicleModels_path
    else
      render :edit
    end
  end

  def create
    @vehicle_model = VehicleModel.new(vehicle_model_params)
    if @vehicle_model.save
      redirect_to vehicleModels_path
    else
      render :new
    end
  end

  private

  def vehicle_model_params
    params.require(:vehicle_model).permit(:vehicle_model_name, :year_of_production, :brand_id)
  end
end

app/helpers/vehicle_models_helper.rb
module VehicleModelsHelper
end

app/views/vehicle_models/_form_vehicle_model_html.erb
<h2>
  <%= title %>
  <%= link_to "", vehicleModels_path, class: 'btn btn-secondary fas fa-undo-alt rounded-1 float-right form-inline' %>
</h2>

<%= form_for @vehicle_model do |f| %>
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <br>
                  <br>
                  <br>
                  <label><b>Model</b></label>
                  <br>
                  <%= f.text_field :vehicle_model_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here vehicle model name', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <label><b>Year of Production</b></label>
                  <br>
                  <%= f.number_field :year_of_production, :type => 'number', :class => 'form-control', :placeholder => 'Enter here year of production', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <label><b>Brand</b></label>
                  <br>
                  <%= f.collection_select(:brand_id, VehicleModel.all.order(:vehicle_model_name), :id, :model_for_select, {:prompt => true}, {:class => 'form-control'}) %>

                  <br>
                  <%= f.submit :Create, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>


<% end %>

app/views/vehicle_models/edit.html.erb
<h2>
  Edit Vehicle Model
  <%= link_to "Return", vehicleModels_path, class: 'btn btn-secondary rounded-1 float-right form-inline' %>
</h2>

<%= form_for @edit_vehicle_model do |f| %>
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <br>
                  <br>
                  <label><b>Brand</b></label>
                  <br>
                  <%= f.collection_select(:brand_id, VehicleModel.all.order(:vehicle_model_name), :id, :model_for_select, {:prompt => true}, {:class => 'form-control'}) %>
                  <br>
                  <label><b>Year of Production</b></label>
                  <br>
                  <%= f.number_field :year_of_production, :type => 'number', :class => 'form-control', :placeholder => 'Enter here year of production', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <label><b>Model</b></label>
                  <br>
                  <%= f.text_field :vehicle_model_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here vehicle model name', autofocus: true, autocomplete: 'off', required: true %>
                  <br>

                  <%= f.submit :Update, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>


<% end %>

app/views/vehicle_models/index.html.erb
<h1>
  Listing vehicle models

  <%= form_tag vehicleModels_path, method: :get, :class => 'float-right form-inline' do %>
    <%= text_field_tag :term, params[:term], autofocus: true, :class => 'form-control mr-sm-2', :type => 'search', :placeholder => 'Search', autocomplete: 'off' %>
    <%= submit_tag 'Search', nombre: nil, :class => 'btn btn-outline-success my-2 my-sm-0' %>&nbsp&nbsp&nbsp&nbsp
    <%= link_to "", models_new_path, class: 'btn btn-primary fas fa-plus rounded-1 float-right form-inline' %>
  <% end %>

</h1>
<br>
<br>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Model</th>
    <th>Year Of Production</th>
    <th>Options</th>
  </tr>
  </thead>

  <% @get_vehicle_models.each do |model| %>
    <tbody>
    <tr>
      <th><%= model.vehicle_model_name %></th>
      <td><%= model.year_of_production %></td>
      <td>
        &nbsp&nbsp<%= link_to "", vehicle_model_edit_path(model),  class:'btn btn-outline rounded-0 fas fa-pencil-alt fa-2x' %>&nbsp&nbsp
      </td>
    </tr>
    </tbody>
  <% end %>
</table>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @get_vehicle_models %>
  </div>
  <%= will_paginate @get_vehicle_models, :container => false %>
</div>

app/views/vehicle_models/new.html.erb
<%= render "vehicle_models/form_vehicle_model_html", title: "New Vehicle Model" %>