config/routes.rb
Rails.application.routes.draw do

  get 'services', to: 'services#index'
  get 'serviceTypes', to: 'service_types#index'
  get 'brands', to: 'brands#index'
  get 'clients', to: 'clients#index'
  get 'colors', to: 'colors#index'
  get 'officials', to: 'officials#index'
  get 'positions', to: 'positions#index'
  get 'vehicleModels', to: 'vehicle_models#index'
  get 'vehicles', to: 'vehicles#index'

  get 'services/new', to: 'services#new', as: 'service_new'
  post 'services', to: 'services#create'

  get 'service/type/new', to: 'service_types#new', as: 'service_types_new'
  post 'service_types', to: 'service_types#create'

  get 'brand/new', to: 'brands#new', as: 'brands_new'
  post 'brands',to: 'brands#create'

  get 'client/new', to: 'clients#new', as: 'clients_new'
  post 'clients', to: 'clients#create'

  get 'color/new', to: 'colors#new', as: 'color_new'
  post 'colors', to: 'colors#create'

  get 'officials/new', to: 'officials#new', as: 'officials_new'
  post 'officials', to: 'officials#create'

  get 'position/new', to: 'positions#new',  as: 'position_new'
  post 'positions', to: 'positions#create'

  get 'vehicleModels/new', to: 'vehicle_models#new', as: 'models_new'
  post 'vehicle_models', to: 'vehicle_models#create'

  get 'vehicle/new', to: 'vehicles#new', as: 'vehicle_new'
  post 'vehicles', to: 'vehicles#create'

  get 'brand/:id', to: 'brands#show', as: 'brand'
  get 'brand/:id/edit', to: 'brands#edit', as: 'brand_edit'
  patch 'brand/:id', to: 'brands#update'

  get 'client/:id', to: 'clients#show', as: 'client'
  get 'client/:id/edit', to: 'clients#edit', as: 'client_edit'
  patch 'client/:id', to: 'clients#update'

  get 'color/:id', to: 'colors#show', as: 'color'
  get 'color/:id/edit', to: 'colors#edit', as: 'color_edit'
  patch 'color/:id', to: 'colors#update'

  get 'official/:id', to: 'officials#show', as: 'official'
  get 'official/:id/edit', to: 'officials#edit', as: 'official_edit'
  patch 'official/:id', to: 'officials#update'

  get 'position/:id', to: 'positions#show', as: 'position'
  get 'position/:id/edit', to: 'positions#edit', as: 'position_edit'
  patch 'position/:id', to: 'positions#update'

  get 'vehicle/model/:id', to: 'vehicle_models#show', as: 'vehicle_model'
  get 'vehicle/model/:id/edit', to: 'vehicle_models#edit', as: 'vehicle_model_edit'
  patch 'vehicle/model/:id', to: 'vehicle_models#update'

  get 'service/type/:id', to: 'service_types#show', as: 'service_type'
  get 'service/type/:id/edit', to: 'service_types#edit', as: 'service_type_edit'
  patch 'service/type/:id', to: 'service_types#update'

  get 'service/:id', to: 'services#show', as: 'service'
  get 'service/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'service/:id', to: 'services#update'

  get 'vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get 'vehicle/:id/edit', to: 'vehicles#edit', as: 'vehicle_edit'
  patch 'vehicle/:id', to: 'vehicles#update'

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :client, optional: true
  belongs_to :color, optional: true
  belongs_to :vehicle_model, optional: true


  def self.search(term, page)
  if term
     where('patent_number LIKE ? or chassis_number LIKE ?', "%#{term}%", "%#{term}%").paginate(page: page, per_page: 5).order('patent_number ASC')
    else
      paginate(page: page, per_page: 4).order('patent_number ASC')
    end
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.search(params[:term],params[:page])
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path
    else
      render :edit
    end
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to vehicles_path
    else
      render :new
    end
  end

  private
  def vehicle_params
    params.require(:vehicle).permit(:patent_number, :chassis_number, :vehicle_models_id, :colors_id, :clients_id)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form_vehicle.html.erb
<h2>
  <%= title %>
  <%= link_to "", vehicles_path, class: 'btn btn-secondary fas fa-undo-alt rounded-1 float-right form-inline' %>
</h2>

<%= form_for @vehicle do |v| %>
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12 col-md-6 mb-3">
              <br>
              <br>
              <label><b>Patent Number</b></label>
              <br>
              <%= v.text_field :patent_number, :type => 'text', :class => 'form-control', :placeholder => 'Enter here patent number', autofocus: true, autocomplete: 'off'%>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <br>
              <br>
              <label><b>Chassis Number</b></label>
              <br>
                <%= v.text_field :chassis_number, :type => 'text', :class => 'form-control', :placeholder => 'Enter here chassis number', autocomplete: 'off', :required => 'true' %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Vehicle Model</b></label>
              <br>
              <%= v.collection_select(:vehicle_models_id, VehicleModel.all.order(:vehicle_model_name), :id, :model_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Color</b></label>
              <br>
                <%= v.collection_select(:colors_id, Color.all.order(:color_name), :id, :color_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Client</b></label>
              <br>
              <%= v.collection_select(:clients_id, Client.all.order(:last_name), :id, :client_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-12 text-center">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <%= v.submit :Create, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/vehicles/edit.html.erb
<h2>
  Edit Vehicle
  <%= link_to "", vehicles_path, class: 'btn btn-secondary fas fa-undo-alt rounded-1 float-right form-inline' %>
</h2>

<%= form_for @vehicle do |edit_vehicle| %>
  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12 col-md-6 mb-3">
              <br>
              <br>
              <label><b>Patent Number</b></label>
              <br>
              <%= edit_vehicle.text_field :patent_number, :type => 'text', :class => 'form-control', :placeholder => 'Enter here patent number', autofocus: true, autocomplete: 'off', :required => 'true' %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <br>
              <br>
              <label><b>Chassis Number</b></label>
              <br>
              <%= edit_vehicle.text_field :chassis_number, :type => 'text', :class => 'form-control', :placeholder => 'Enter here chassis number', autocomplete: 'off', :required => 'true' %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Vehicle Model</b></label>
              <br>
              <%= edit_vehicle.collection_select(:vehicle_models_id, VehicleModel.all.order(:vehicle_model_name), :id, :model_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Color</b></label>
              <br>
              <%= edit_vehicle.collection_select(:colors_id, Color.all.order(:color_name), :id, :color_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
            <div class="col-12 col-md-6 mb-3">
              <label><b>Client</b></label>
              <br>
              <%= edit_vehicle.collection_select(:clients_id, Client.all.order(:last_name), :id, :client_for_select, {:prompt => true}, {:class => 'form-control'}) %>
              <br>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-12 text-center">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <%= edit_vehicle.submit :Update, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/vehicles/index.html.erb
<h1>
  Listings Vehicles

  <%= form_tag vehicles_path, method: :get, :class => 'float-right form-inline' do %>
    <%= text_field_tag :term, params[:term], autofocus: true, :class => 'form-control mr-sm-2', :type => 'search', :placeholder => 'Search', autocomplete: 'off' %>
    <%= submit_tag 'Search', nombre: nil, :class => 'btn btn-outline-success my-2 my-sm-0' %>&nbsp&nbsp&nbsp&nbsp
    <%= link_to "", vehicle_new_path, class: 'btn btn-primary fas fa-plus rounded-1 float-right form-inline' %>
  <% end %>

</h1>
<br>
<br>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Patent Number</th>
    <th>Chassis Number</th>
    <th>Client</th>
    <th>Color</th>
    <th>Model</th>
    <th>Edit or View</th>
  </tr>
  </thead>
  <% @vehicles.each  do |vehicle| %>
    <tbody>
    <tr>
      <th><%= vehicle.patent_number %></th>
      <td><%= vehicle.chassis_number %></td>
      <td><%= vehicle.client.clients_id.first_name %></td>
      <td><%= vehicle.colors_id %></td>
      <td><%= vehicle.vehicle_models_id %></td>
      <td>
        &nbsp&nbsp<%= link_to "", vehicle_edit_path(vehicle),  class:'btn btn-outline rounded-0 fas fa-pencil-alt fa-2x' %>&nbsp&nbsp
      </td>
    </tr>
    </tbody>
  <% end %>

</table>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @vehicle_list %>
  </div>
  <%= will_paginate @vehicle_list, :container => false %>
</div>



app/views/vehicles/new.html.erb
<%= render "vehicles/form_vehicle", title: "New Vehicle " %>