config/routes.rb
Rails.application.routes.draw do

  get 'services', to: 'services#index'
  get 'serviceTypes', to: 'service_types#index'
  get 'brands', to: 'brands#index'
  get 'clients', to: 'clients#index'
  get 'colors', to: 'colors#index'
  get 'officials', to: 'officials#index'
  get 'positions', to: 'positions#index'
  get 'vehicleModels', to: 'vehicle_models#index'
  get 'vehicles', to: 'vehicles#index'

  get 'services/new', to: 'services#new', as: 'service_new'
  post 'services', to: 'services#create'

  get 'service/type/new', to: 'service_types#new', as: 'service_types_new'
  post 'service_types', to: 'service_types#create'

  get 'brand/new', to: 'brands#new', as: 'brands_new'
  post 'brands',to: 'brands#create'

  get 'client/new', to: 'clients#new', as: 'clients_new'
  post 'clients', to: 'clients#create'

  get 'color/new', to: 'colors#new', as: 'color_new'
  post 'colors', to: 'colors#create'

  get 'officials/new', to: 'officials#new', as: 'officials_new'
  post 'officials', to: 'officials#create'

  get 'position/new', to: 'positions#new',  as: 'position_new'
  post 'positions', to: 'positions#create'

  get 'vehicleModels/new', to: 'vehicle_models#new', as: 'models_new'
  post 'vehicle_models', to: 'vehicle_models#create'

  get 'vehicle/new', to: 'vehicles#new', as: 'vehicle_new'
  post 'vehicles', to: 'vehicles#create'

  get 'brand/:id', to: 'brands#show', as: 'brand'
  get 'brand/:id/edit', to: 'brands#edit', as: 'brand_edit'
  patch 'brand/:id', to: 'brands#update'

  get 'client/:id', to: 'clients#show', as: 'client'
  get 'client/:id/edit', to: 'clients#edit', as: 'client_edit'
  patch 'client/:id', to: 'clients#update'

  get 'color/:id', to: 'colors#show', as: 'color'
  get 'color/:id/edit', to: 'colors#edit', as: 'color_edit'
  patch 'color/:id', to: 'colors#update'

  get 'official/:id', to: 'officials#show', as: 'official'
  get 'official/:id/edit', to: 'officials#edit', as: 'official_edit'
  patch 'official/:id', to: 'officials#update'

  get 'position/:id', to: 'positions#show', as: 'position'
  get 'position/:id/edit', to: 'positions#edit', as: 'position_edit'
  patch 'position/:id', to: 'positions#update'

  get 'vehicle/model/:id', to: 'vehicle_models#show', as: 'vehicle_model'
  get 'vehicle/model/:id/edit', to: 'vehicle_models#edit', as: 'vehicle_model_edit'
  patch 'vehicle/model/:id', to: 'vehicle_models#update'

  get 'service/type/:id', to: 'service_types#show', as: 'service_type'
  get 'service/type/:id/edit', to: 'service_types#edit', as: 'service_type_edit'
  patch 'service/type/:id', to: 'service_types#update'

  get 'service/:id', to: 'services#show', as: 'service'
  get 'service/:id/edit', to: 'services#edit', as: 'service_edit'
  patch 'service/:id', to: 'services#update'

  get 'vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get 'vehicle/:id/edit', to: 'vehicles#edit', as: 'vehicle_edit'
  patch 'vehicle/:id', to: 'vehicles#update'

end

app/models/brand.rb
class Brand < ApplicationRecord
 has_many :vehicle_models
 validates :brand_name, presence: true

 def self.search(term, page)
  if term
   where('brand_name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('brand_name ASC')
  else
   paginate(page: page, per_page: 4).order('brand_name ASC')
  end
 end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @get_brands_list = Brand.search(params[:term], params[:page])
  end

  def new
    @brand_new = Brand.new
  end

  def edit
    @edit_brand = Brand.find(params[:id])
  end

  def update
    @brand_update = Brand.find(params[:id])
    if @brand_update.update(brand_params)
      redirect_to brands_path
    else
      render :edit
    end
  end

  def create
    @brand_new = Brand.new(brand_params)
    if @brand_new.save
      redirect_to brands_path
    else
      render :new
    end
  end

  private
  def brand_params
    params.require(:brand).permit(:brand_name)
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form_brand.html.erb
<h2>
  <%= title %>
  <%= link_to "", brands_path, class: 'btn btn-secondary fas fa-undo-alt rounded-1 float-right form-inline' %>
</h2>

<%= form_for @brand_new do |f| %>

<div class="container">
  <div class="row mt-3">
    <div class="col">
      <form action="">
        <div class="form-group row">
          <div class="col-12">
            <div class="row justify-content-center">
              <div class="col-12 col-sm-9 col-md-4">
                <br>
                <br>
                <br>
                <br>
                <label><b>Marcas</b></label>
                <br>
                <%= f.text_field :brand_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here brand name', autofocus: true, autocomplete: 'off', required: true %>
                <br>
                <%= f.submit :Create, :class => 'btn btn-primary btn-block' %>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<% end %>

app/views/brands/edit.html.erb
<h2>
  Edit brand
  <%= link_to "Return", brands_path, class: 'btn btn-secondary rounded-1 float-right form-inline' %>
</h2>

<%= form_for  @edit_brand do |f| %>

  <div class="container">
    <div class="row mt-3">
      <div class="col">
        <form action="">
          <div class="form-group row">
            <div class="col-12">
              <div class="row justify-content-center">
                <div class="col-12 col-sm-9 col-md-4">
                  <br>
                  <br>
                  <br>
                  <br>
                  <label><b>Brand</b></label>
                  <br>
                  <%= f.text_field :brand_name, :type => 'text', :class => 'form-control', :placeholder => 'Enter here brand name', autofocus: true, autocomplete: 'off', required: true %>
                  <br>
                  <%= f.submit :Update, :class => 'btn btn-primary btn-block' %>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

<% end %>

app/views/brands/index.html.erb
<h1>
  Listado de Marcas

  <%= form_tag brands_path, method: :get, :class => 'float-right form-inline' do %>
    <%= text_field_tag :term, params[:term], autofocus: true, :class => 'form-control mr-sm-2', :type => 'search', :placeholder => 'nombre de marca', autocomplete: 'off' %>
    <%= submit_tag 'Buscar', nombre: nil, :class => 'btn btn-outline-success my-2 my-sm-0' %>&nbsp&nbsp&nbsp&nbsp
    <%= link_to "", brands_new_path, class: 'btn btn-primary fas fa-plus rounded-1 float-right form-inline' %>
  <% end %>

</h1>
<br>
<br>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Marcas</th>
    <th>Ver o Editar</th>
  </tr>
  </thead>

  <% @get_brands_list.each do |brand| %>
    <tbody>
    <tr>
      <th>&nbsp&nbsp<%= brand.brand_name %>&nbsp&nbsp</th>
      <td>
        &nbsp&nbsp<%= link_to "", brand_edit_path(brand), class:'btn btn-outline rounded-0 fas fa-pencil-alt fa-2x' %>&nbsp&nbsp

      </td>
    </tr>
    </tbody>
  <% end %>
</table>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @get_brands_list %>
  </div>
  <%= will_paginate @get_brands_list, :container => false %>
</div>

app/views/brands/new.html.erb
<%= render "brands/form_brand", title: "New Brand" %>
